services:
  - type: cron
    name: bill-social-poster-business
    env: python
    schedule: "45 10 * * *"   # 10:45 AM UTC = 3:45 AM MST (UTC-7)
    buildCommand: pip install -r requirements.txt && npm install -g @zernio/cli
    startCommand: python post.py
    envVars:
      - key: ZERNIO_KEY
        value: sk_765d2e08eb72d83199029aa5274ea95ee9102aca93d8a8442b7dde6163a942e7
      - key: IG_ACCOUNT
        value: 6a12f65a2b2567671a2a90d6
      - key: LI_ACCOUNT
        value: 6a12f6ac2b2567671a2a931a
      - key: POST_TYPE
        value: business
  - type: cron
    name: bill-social-poster-personal
    env: python
    schedule: "15 17 * * *"   # 17:15 PM UTC = 10:15 AM MST (UTC-7)
    buildCommand: pip install -r requirements.txt && npm install -g @zernio/cli
    startCommand: python post.py
    envVars:
      - key: ZERNIO_KEY
        value: sk_765d2e08eb72d83199029aa5274ea95ee9102aca93d8a8442b7dde6163a942e7
      - key: IG_ACCOUNT
        value: 6a12f65a2b2567671a2a90d6
      - key: LI_ACCOUNT
        value: 6a12f6ac2b2567671a2a931a
      - key: POST_TYPE
        value: personal
